# Generated by Django 4.1.1 on 2022-10-20 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_prospects_remove_users_waiting_list_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255)),
                ('area_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('External_contacts_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalRelationsObjetives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('External_relations_objetives_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InternalContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_contacts_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InternalRelationsObjetives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Internal_relations_objetives_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=255)),
                ('language_level', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=255)),
                ('level_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession_degree_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.CharField(max_length=255)),
                ('years_of_experience', models.IntegerField()),
                ('purpose', models.CharField(max_length=255)),
                ('immediate_position_superior', models.CharField(max_length=255)),
                ('aditional_knowledge', models.CharField(max_length=255)),
                ('responsabilities', models.CharField(max_length=255)),
                ('laboral_conditions', models.CharField(max_length=255)),
                ('competencies', models.CharField(max_length=255)),
                ('date_of_entry', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
                ('prospects_limits', models.IntegerField()),
                ('users_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VacanciesProspects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prospects_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.prospects')),
                ('vacancies_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancies')),
            ],
        ),
        migrations.CreateModel(
            name='VacanciesProfessionDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession_degree_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.professiondegree')),
                ('vacancies_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancies')),
            ],
        ),
        migrations.CreateModel(
            name='VacanciesProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.profession')),
                ('vacancies_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancies')),
            ],
        ),
        migrations.CreateModel(
            name='VacanciesLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.levels')),
                ('vacancies_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancies')),
            ],
        ),
        migrations.CreateModel(
            name='VacanciesLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.languages')),
                ('vacancies_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancies')),
            ],
        ),
        migrations.CreateModel(
            name='VacanciesInternalRelationsObjetives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Internal_relations_objetives_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.internalrelationsobjetives')),
                ('vacancies_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancies')),
            ],
        ),
        migrations.CreateModel(
            name='VacanciesInternalContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_contacts_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.internalcontacts')),
                ('vacancies_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancies')),
            ],
        ),
        migrations.CreateModel(
            name='VacanciesExternalRelationsObjetives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('External_relations_objetives_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.externalrelationsobjetives')),
                ('vacancies_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancies')),
            ],
        ),
        migrations.CreateModel(
            name='VacanciesExternalContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('External_contacts_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.externalcontacts')),
                ('vacancies_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancies')),
            ],
        ),
        migrations.CreateModel(
            name='VacanciesAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.areas')),
                ('vacancies_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancies')),
            ],
        ),
        migrations.CreateModel(
            name='LevelsAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.areas')),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.levels')),
            ],
        ),
    ]
