# Generated by Django 4.1.1 on 2022-10-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_groups_deactivated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='document_type',
            field=models.CharField(choices=[('C.C', 'Cédula de ciudadanía'), ('NIT', 'NIT'), ('C.E', 'Cédula de extranjería')], max_length=3, verbose_name='Tipo de documento'),
        ),
    ]
