# Generated by Django 4.1.1 on 2022-10-20 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('document_type', models.CharField(choices=[('C.C', 'Cédula de ciudadanía'), ('NIT', 'NIT'), ('C.E', 'Cédula de extranjería'), ('T.I', 'Tarjeta de identidad')], max_length=3, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=255, verbose_name='Número de documento')),
                ('waiting_list', models.BooleanField(default=False)),
                ('prospect_cv', models.CharField(max_length=255, verbose_name='Hoja de vida')),
                ('postulated_date', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('ENP', 'En proceso'), ('AP', 'Aplicó'), ('NP', 'Ningún proceso')], default='NP', max_length=3, verbose_name='Estado del proceso')),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='waiting_list',
        ),
        migrations.AlterField(
            model_name='users',
            name='document_type',
            field=models.CharField(choices=[('C.C', 'Cédula de ciudadanía'), ('NIT', 'NIT'), ('C.E', 'Cédula de extranjería'), ('T.I', 'Tarjeta de identidad')], max_length=3, verbose_name='Tipo de documento'),
        ),
        migrations.AddField(
            model_name='users',
            name='prospect',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.prospects'),
            preserve_default=False,
        ),
    ]
