from django.urls import path
from apps.vacancies.views.MastersViews import (LanguagesMasterView,AreasMasterView, LevelMasterView,ProfessionMasterView,ProfessionDegreeMasterView,LevelsAreasMasterView,
InternalContactsMasterView,LanguagesLanguagesLevelsView,InternalRelationsObjetivesMasterView,ExternalContactsMasterView,ExternalRelationsObjetivesMasterView,LevelsRelatedAreasView,LanguagesLevelMasterView)

urlpatterns = [
    path('master/languages/',LanguagesMasterView.as_view(),name="master-language"),
    path('master/languages/<int:pk>/',LanguagesMasterView.as_view(),name="master-language-id"),
    path('master/languages-level/',LanguagesLevelMasterView.as_view(),name="master-language-level"),
    path('master/languages-level/<int:pk>/',LanguagesLevelMasterView.as_view(),name="master-language-level-id"),
    path('master/languages-rel-level/',LanguagesLanguagesLevelsView.as_view(),name="master-language-rel-level"),
    path('master/languages-rel-level/<int:pk>/',LanguagesLanguagesLevelsView.as_view(),name="master-language-rel-level-id"),
    path('master/areas/',AreasMasterView.as_view(),name="masterArea"),
    path('master/areas/<int:pk>/',AreasMasterView.as_view(),name="masterAreaId"),
    path('master/levels/',LevelMasterView.as_view(),name="masterLevel"),
    path('master/levels/<int:pk>/',LevelMasterView.as_view(),name="masterLevelId"),
    path('master/levels-areas/',LevelsAreasMasterView.as_view(),name="master-level-areas"),
    path('master/levels-relations-areas/',LevelsRelatedAreasView.as_view(),name="master-level-related-areas"),
    # path('master/levels-areas/<int:pk>/',LevelsAreasMasterView.as_view(),name="master-level-areasId"),
    path('master/professions/',ProfessionMasterView.as_view(),name="masterProfession"),
    path('master/professions/<int:pk>/',ProfessionMasterView.as_view(),name="masterProfessionId"),
    path('master/professionsDegree/',ProfessionDegreeMasterView.as_view(),name="masterProfessionDegree"),
    path('master/professionsDegree/<int:pk>/',ProfessionDegreeMasterView.as_view(),name="masterProfessionDegreeId"),
    path('master/internalContacts/',InternalContactsMasterView.as_view(),name="master-internal-contact"),
    path('master/internalContacts/<int:pk>/',InternalContactsMasterView.as_view(),name="master-internal-contact-id"),
    path('master/internalRelationsObjetives/',InternalRelationsObjetivesMasterView.as_view(),name="master-internal-relations-objetives"),
    path('master/internalRelationsObjetives/<int:pk>/',InternalRelationsObjetivesMasterView.as_view(),name="master-internal-relations-objetives-id"),
    path('master/externalContacts/',ExternalContactsMasterView.as_view(),name="master-external-contacts"),
    path('master/externalContacts/<int:pk>/',ExternalContactsMasterView.as_view(),name="master-external-contacts-id"),
    path('master/externalRelationsObjetives/',ExternalRelationsObjetivesMasterView.as_view(),name="master-external-relations-objetives"),
    path('master/externalRelationsObjetives/<int:pk>/',ExternalRelationsObjetivesMasterView.as_view(),name="master-external-relations-objetives-id"),
]